// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package repository

import (
	"context"
)

const listAllDisputes = `-- name: ListAllDisputes :many
SELECT id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at FROM disputes
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDisputesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDisputes(ctx context.Context, arg ListAllDisputesParams) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listAllDisputes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.AmountMinor,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.Evidence,
			&i.NetworkRef,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMerchants = `-- name: ListAllMerchants :many

SELECT id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash FROM merchants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllMerchantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// internal/repository/queries/admin.sql
// Platform (admin) read models behind X-Admin-Key. These are intentionally
// unscoped by merchant — they power the operator console. All parameters are
// bound ($1, $2, ...) so there is no SQL-injection surface.
func (q *Queries) ListAllMerchants(ctx context.Context, arg ListAllMerchantsParams) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listAllMerchants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.ApiKeyHash,
			&i.Mcc,
			&i.SettlementCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookUrl,
			&i.WebhookSecretHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor, action, entity_type, entity_id, metadata, created_at FROM audit_log
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformStats = `-- name: PlatformStats :one
SELECT
    COUNT(*)::BIGINT AS payment_count,
    COALESCE(SUM(
        CASE WHEN status IN ('captured', 'partial_refunded', 'refunded')
             THEN captured_amount_minor ELSE 0 END
    ), 0)::BIGINT AS volume_minor,
    COALESCE(SUM(
        CASE WHEN status IN ('authorized', 'captured', 'partial_refunded', 'refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS authorized_count,
    COALESCE(SUM(
        CASE WHEN status IN ('captured', 'partial_refunded', 'refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS captured_count,
    COALESCE(SUM(
        CASE WHEN status IN ('refunded', 'partial_refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS refunded_count,
    COALESCE(SUM(
        CASE WHEN status = 'failed' THEN 1 ELSE 0 END
    ), 0)::BIGINT AS failed_count,
    (SELECT COUNT(*) FROM merchants)::BIGINT AS merchant_count,
    (SELECT COUNT(*) FROM disputes)::BIGINT  AS dispute_count
FROM payments
`

type PlatformStatsRow struct {
	PaymentCount    int64 `json:"payment_count"`
	VolumeMinor     int64 `json:"volume_minor"`
	AuthorizedCount int64 `json:"authorized_count"`
	CapturedCount   int64 `json:"captured_count"`
	RefundedCount   int64 `json:"refunded_count"`
	FailedCount     int64 `json:"failed_count"`
	MerchantCount   int64 `json:"merchant_count"`
	DisputeCount    int64 `json:"dispute_count"`
}

// Platform-wide key risk indicators across every merchant. Volume is captured
// (net-of-refund) minor units. merchant_count is a cheap correlated count.
func (q *Queries) PlatformStats(ctx context.Context) (PlatformStatsRow, error) {
	row := q.db.QueryRow(ctx, platformStats)
	var i PlatformStatsRow
	err := row.Scan(
		&i.PaymentCount,
		&i.VolumeMinor,
		&i.AuthorizedCount,
		&i.CapturedCount,
		&i.RefundedCount,
		&i.FailedCount,
		&i.MerchantCount,
		&i.DisputeCount,
	)
	return i, err
}
