// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkout_session.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCheckoutSession = `-- name: CreateCheckoutSession :one

INSERT INTO checkout_sessions (
    id, merchant_id, payment_link_id, session_token_hash, amount_minor, currency,
    status, selected_method, payment_id, qr_payment_id, customer_email, return_url, expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, merchant_id, payment_link_id, session_token_hash, amount_minor, currency, status, selected_method, payment_id, qr_payment_id, customer_email, return_url, expires_at, created_at, updated_at
`

type CreateCheckoutSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	PaymentLinkID    pgtype.UUID        `json:"payment_link_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	AmountMinor      int64              `json:"amount_minor"`
	Currency         string             `json:"currency"`
	Status           string             `json:"status"`
	SelectedMethod   string             `json:"selected_method"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	QrPaymentID      pgtype.UUID        `json:"qr_payment_id"`
	CustomerEmail    string             `json:"customer_email"`
	ReturnUrl        string             `json:"return_url"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// internal/repository/queries/checkout_session.sql
// Hosted-checkout sessions. A session is ALWAYS resolved by its token hash (the
// token is the credential); the merchant scope comes from the resolved row, not
// from the caller. Updates are by primary key (already resolved from the hash).
func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.ID,
		arg.MerchantID,
		arg.PaymentLinkID,
		arg.SessionTokenHash,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.SelectedMethod,
		arg.PaymentID,
		arg.QrPaymentID,
		arg.CustomerEmail,
		arg.ReturnUrl,
		arg.ExpiresAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentLinkID,
		&i.SessionTokenHash,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.SelectedMethod,
		&i.PaymentID,
		&i.QrPaymentID,
		&i.CustomerEmail,
		&i.ReturnUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionByTokenHash = `-- name: GetCheckoutSessionByTokenHash :one
SELECT id, merchant_id, payment_link_id, session_token_hash, amount_minor, currency, status, selected_method, payment_id, qr_payment_id, customer_email, return_url, expires_at, created_at, updated_at FROM checkout_sessions WHERE session_token_hash = $1
`

func (q *Queries) GetCheckoutSessionByTokenHash(ctx context.Context, sessionTokenHash string) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByTokenHash, sessionTokenHash)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentLinkID,
		&i.SessionTokenHash,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.SelectedMethod,
		&i.PaymentID,
		&i.QrPaymentID,
		&i.CustomerEmail,
		&i.ReturnUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCheckoutSession = `-- name: UpdateCheckoutSession :one
UPDATE checkout_sessions
SET status = $2, selected_method = $3, payment_id = $4, qr_payment_id = $5,
    customer_email = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, merchant_id, payment_link_id, session_token_hash, amount_minor, currency, status, selected_method, payment_id, qr_payment_id, customer_email, return_url, expires_at, created_at, updated_at
`

type UpdateCheckoutSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	SelectedMethod string      `json:"selected_method"`
	PaymentID      pgtype.UUID `json:"payment_id"`
	QrPaymentID    pgtype.UUID `json:"qr_payment_id"`
	CustomerEmail  string      `json:"customer_email"`
}

func (q *Queries) UpdateCheckoutSession(ctx context.Context, arg UpdateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, updateCheckoutSession,
		arg.ID,
		arg.Status,
		arg.SelectedMethod,
		arg.PaymentID,
		arg.QrPaymentID,
		arg.CustomerEmail,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentLinkID,
		&i.SessionTokenHash,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.SelectedMethod,
		&i.PaymentID,
		&i.QrPaymentID,
		&i.CustomerEmail,
		&i.ReturnUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
