// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDisputesByMerchant = `-- name: CountDisputesByMerchant :one
SELECT COUNT(*)::BIGINT AS dispute_count
FROM disputes
WHERE merchant_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type CountDisputesByMerchantParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

// Chargeback count for a merchant over the same window, used to derive the
// chargeback ratio against total payment count.
func (q *Queries) CountDisputesByMerchant(ctx context.Context, arg CountDisputesByMerchantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDisputesByMerchant, arg.MerchantID, arg.CreatedAt, arg.CreatedAt_2)
	var dispute_count int64
	err := row.Scan(&dispute_count)
	return dispute_count, err
}

const listAllPayouts = `-- name: ListAllPayouts :many
SELECT id, merchant_id, currency, gross_minor, refunded_minor, fee_minor, net_minor, payment_count, status, period_start, period_end, created_at FROM payouts
ORDER BY created_at DESC
LIMIT $1
`

// Platform-wide settlement / payout rows for the admin console, most recent
// first. Unscoped (admin-only) — authorization is enforced by AdminAuth.
func (q *Queries) ListAllPayouts(ctx context.Context, limit int32) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listAllPayouts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Currency,
			&i.GrossMinor,
			&i.RefundedMinor,
			&i.FeeMinor,
			&i.NetMinor,
			&i.PaymentCount,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByMerchant = `-- name: ListPayoutsByMerchant :many
SELECT id, merchant_id, currency, gross_minor, refunded_minor, fee_minor, net_minor, payment_count, status, period_start, period_end, created_at FROM payouts
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsByMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// Settlement / payout rows for a merchant, most recent first.
func (q *Queries) ListPayoutsByMerchant(ctx context.Context, arg ListPayoutsByMerchantParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Currency,
			&i.GrossMinor,
			&i.RefundedMinor,
			&i.FeeMinor,
			&i.NetMinor,
			&i.PaymentCount,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantStats = `-- name: MerchantStats :one

SELECT
    COUNT(*)::BIGINT AS count,
    COALESCE(SUM(
        CASE WHEN status IN ('captured', 'partial_refunded', 'refunded')
             THEN captured_amount_minor ELSE 0 END
    ), 0)::BIGINT AS volume_minor,
    COALESCE(SUM(
        CASE WHEN status IN ('authorized', 'captured', 'partial_refunded', 'refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS authorized_count,
    COALESCE(SUM(
        CASE WHEN status IN ('captured', 'partial_refunded', 'refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS captured_count,
    COALESCE(SUM(
        CASE WHEN status IN ('refunded', 'partial_refunded')
             THEN 1 ELSE 0 END
    ), 0)::BIGINT AS refunded_count,
    COALESCE(SUM(
        CASE WHEN status = 'failed' THEN 1 ELSE 0 END
    ), 0)::BIGINT AS failed_count
FROM payments
WHERE merchant_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type MerchantStatsParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type MerchantStatsRow struct {
	Count           int64 `json:"count"`
	VolumeMinor     int64 `json:"volume_minor"`
	AuthorizedCount int64 `json:"authorized_count"`
	CapturedCount   int64 `json:"captured_count"`
	RefundedCount   int64 `json:"refunded_count"`
	FailedCount     int64 `json:"failed_count"`
}

// internal/repository/queries/dashboard.sql
// Merchant Dashboard read models: KPI aggregation over payments, the merchant's
// own settlement/payout rows, and its full dispute list. Everything is scoped to
// the authenticated merchant id ($1) so there is no cross-tenant leakage. All
// parameters are bound ($1, $2, ...) so there is no SQL-injection surface.
// One-row KPI rollup for a merchant over an inclusive [from, to] window. Volume
// is captured (net-of-refund) money in minor units; the by-status counts drive
// the dashboard tiles and the success / refund ratios. authorized here means
// "reached authorized or beyond" (authorized|captured|partial_refunded|refunded)
// so the success rate reflects payments that were approved by the acquirer.
func (q *Queries) MerchantStats(ctx context.Context, arg MerchantStatsParams) (MerchantStatsRow, error) {
	row := q.db.QueryRow(ctx, merchantStats, arg.MerchantID, arg.CreatedAt, arg.CreatedAt_2)
	var i MerchantStatsRow
	err := row.Scan(
		&i.Count,
		&i.VolumeMinor,
		&i.AuthorizedCount,
		&i.CapturedCount,
		&i.RefundedCount,
		&i.FailedCount,
	)
	return i, err
}

const statsSeriesByDay = `-- name: StatsSeriesByDay :many
SELECT
    date_trunc('day', created_at)::date AS day,
    COALESCE(SUM(
        CASE WHEN status IN ('captured', 'partial_refunded', 'refunded')
             THEN captured_amount_minor ELSE 0 END
    ), 0)::BIGINT AS volume_minor,
    COUNT(*)::BIGINT AS count
FROM payments
WHERE merchant_id = $1
  AND created_at >= $2
  AND created_at < $3
GROUP BY 1
ORDER BY 1
`

type StatsSeriesByDayParams struct {
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type StatsSeriesByDayRow struct {
	Day         pgtype.Date `json:"day"`
	VolumeMinor int64       `json:"volume_minor"`
	Count       int64       `json:"count"`
}

// Daily payment series for a merchant over the half-open window [from, to),
// bucketed by UTC calendar day. Volume uses the SAME captured (net-of-refund)
// definition as MerchantStats (captured/partial_refunded/refunded rows only);
// count is every payment created that day regardless of status. Days with no
// payments are simply absent from the result set — the service zero-fills them
// so the dashboard sparkline has one point per day.
func (q *Queries) StatsSeriesByDay(ctx context.Context, arg StatsSeriesByDayParams) ([]StatsSeriesByDayRow, error) {
	rows, err := q.db.Query(ctx, statsSeriesByDay, arg.MerchantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsSeriesByDayRow
	for rows.Next() {
		var i StatsSeriesByDayRow
		if err := rows.Scan(&i.Day, &i.VolumeMinor, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
