// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispute.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDispute = `-- name: CreateDispute :one

INSERT INTO disputes (
    id, payment_id, merchant_id, amount_minor, currency, reason, status, network_ref
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at
`

type CreateDisputeParams struct {
	ID          pgtype.UUID `json:"id"`
	PaymentID   pgtype.UUID `json:"payment_id"`
	MerchantID  pgtype.UUID `json:"merchant_id"`
	AmountMinor int64       `json:"amount_minor"`
	Currency    string      `json:"currency"`
	Reason      *string     `json:"reason"`
	Status      string      `json:"status"`
	NetworkRef  *string     `json:"network_ref"`
}

// internal/repository/queries/dispute.sql
// Chargeback / dispute data access. State machine transitions are enforced in
// the service layer; these queries persist the resulting rows. All parameters
// are bound ($1, $2, ...).
func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.ID,
		arg.PaymentID,
		arg.MerchantID,
		arg.AmountMinor,
		arg.Currency,
		arg.Reason,
		arg.Status,
		arg.NetworkRef,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.Evidence,
		&i.NetworkRef,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at FROM disputes WHERE id = $1
`

func (q *Queries) GetDispute(ctx context.Context, id pgtype.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.Evidence,
		&i.NetworkRef,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDisputesByMerchant = `-- name: ListDisputesByMerchant :many
SELECT id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at FROM disputes
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDisputesByMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListDisputesByMerchant(ctx context.Context, arg ListDisputesByMerchantParams) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputesByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.AmountMinor,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.Evidence,
			&i.NetworkRef,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesByPayment = `-- name: ListDisputesByPayment :many
SELECT id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at FROM disputes
WHERE payment_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDisputesByPayment(ctx context.Context, paymentID pgtype.UUID) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputesByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.MerchantID,
			&i.AmountMinor,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.Evidence,
			&i.NetworkRef,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisputeStatus = `-- name: UpdateDisputeStatus :one
UPDATE disputes
SET status = $2,
    evidence = COALESCE($3, evidence),
    resolved_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, payment_id, merchant_id, amount_minor, currency, reason, status, evidence, network_ref, opened_at, resolved_at, created_at, updated_at
`

type UpdateDisputeStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	Evidence   []byte             `json:"evidence"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, updateDisputeStatus,
		arg.ID,
		arg.Status,
		arg.Evidence,
		arg.ResolvedAt,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.Evidence,
		&i.NetworkRef,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
