// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant_user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchantUser = `-- name: CreateMerchantUser :one
INSERT INTO merchant_users (
    id, merchant_id, email, name, avatar_url, oauth_provider, oauth_subject
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, email, name, avatar_url, oauth_provider, oauth_subject, role, last_login_at, created_at, updated_at
`

type CreateMerchantUserParams struct {
	ID            pgtype.UUID `json:"id"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	AvatarUrl     string      `json:"avatar_url"`
	OauthProvider string      `json:"oauth_provider"`
	OauthSubject  string      `json:"oauth_subject"`
}

func (q *Queries) CreateMerchantUser(ctx context.Context, arg CreateMerchantUserParams) (MerchantUser, error) {
	row := q.db.QueryRow(ctx, createMerchantUser,
		arg.ID,
		arg.MerchantID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.OauthProvider,
		arg.OauthSubject,
	)
	var i MerchantUser
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantUserByID = `-- name: GetMerchantUserByID :one
SELECT id, merchant_id, email, name, avatar_url, oauth_provider, oauth_subject, role, last_login_at, created_at, updated_at FROM merchant_users WHERE id = $1
`

func (q *Queries) GetMerchantUserByID(ctx context.Context, id pgtype.UUID) (MerchantUser, error) {
	row := q.db.QueryRow(ctx, getMerchantUserByID, id)
	var i MerchantUser
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantUserByOAuth = `-- name: GetMerchantUserByOAuth :one

SELECT id, merchant_id, email, name, avatar_url, oauth_provider, oauth_subject, role, last_login_at, created_at, updated_at FROM merchant_users
WHERE oauth_provider = $1 AND oauth_subject = $2
`

type GetMerchantUserByOAuthParams struct {
	OauthProvider string `json:"oauth_provider"`
	OauthSubject  string `json:"oauth_subject"`
}

// internal/repository/queries/merchant_user.sql
// Dashboard human identities. Login resolves a user by (provider, subject); a
// first-time identity is created together with its merchant by the service layer.
func (q *Queries) GetMerchantUserByOAuth(ctx context.Context, arg GetMerchantUserByOAuthParams) (MerchantUser, error) {
	row := q.db.QueryRow(ctx, getMerchantUserByOAuth, arg.OauthProvider, arg.OauthSubject)
	var i MerchantUser
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchMerchantUserLogin = `-- name: TouchMerchantUserLogin :exec
UPDATE merchant_users SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchMerchantUserLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMerchantUserLogin, id)
	return err
}
