// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one

INSERT INTO merchants (
    id, name, mcc, settlement_currency, api_key_hash
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash
`

type CreateMerchantParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Mcc                *string     `json:"mcc"`
	SettlementCurrency string      `json:"settlement_currency"`
	ApiKeyHash         string      `json:"api_key_hash"`
}

// internal/repository/queries/merchant.sql
// Merchant onboarding and lookup. The raw API key is never stored — only its
// hash (api_key_hash). Auth resolves a merchant by hashing the presented key and
// matching it here. All parameters are bound ($1, $2, ...).
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.Mcc,
		arg.SettlementCurrency,
		arg.ApiKeyHash,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApiKeyHash,
		&i.Mcc,
		&i.SettlementCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretHash,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApiKeyHash,
		&i.Mcc,
		&i.SettlementCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretHash,
	)
	return i, err
}

const getMerchantByAPIKeyHash = `-- name: GetMerchantByAPIKeyHash :one
SELECT id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash FROM merchants
WHERE api_key_hash = $1 AND status = 'active'
`

func (q *Queries) GetMerchantByAPIKeyHash(ctx context.Context, apiKeyHash string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByAPIKeyHash, apiKeyHash)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApiKeyHash,
		&i.Mcc,
		&i.SettlementCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretHash,
	)
	return i, err
}

const rotateMerchantAPIKey = `-- name: RotateMerchantAPIKey :one
UPDATE merchants
SET api_key_hash = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash
`

type RotateMerchantAPIKeyParams struct {
	ID         pgtype.UUID `json:"id"`
	ApiKeyHash string      `json:"api_key_hash"`
}

// Issues a new API key by replacing the stored hash. The previous hash no
// longer resolves, so the old key is immediately invalidated. The raw key is
// generated and returned by the service layer; only its hash is persisted here.
func (q *Queries) RotateMerchantAPIKey(ctx context.Context, arg RotateMerchantAPIKeyParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, rotateMerchantAPIKey, arg.ID, arg.ApiKeyHash)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApiKeyHash,
		&i.Mcc,
		&i.SettlementCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretHash,
	)
	return i, err
}

const setMerchantWebhook = `-- name: SetMerchantWebhook :one
UPDATE merchants
SET webhook_url = $2,
    webhook_secret_hash = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, api_key_hash, mcc, settlement_currency, created_at, updated_at, webhook_url, webhook_secret_hash
`

type SetMerchantWebhookParams struct {
	ID                pgtype.UUID `json:"id"`
	WebhookUrl        *string     `json:"webhook_url"`
	WebhookSecretHash *string     `json:"webhook_secret_hash"`
}

// Sets the merchant's outbound webhook URL and rotates its delivery signing
// secret. Only the hash of the signing secret is stored; the raw secret is
// returned once by the service layer.
func (q *Queries) SetMerchantWebhook(ctx context.Context, arg SetMerchantWebhookParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, setMerchantWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecretHash)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApiKeyHash,
		&i.Mcc,
		&i.SettlementCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.WebhookSecretHash,
	)
	return i, err
}
