// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CheckoutSession struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	PaymentLinkID    pgtype.UUID        `json:"payment_link_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	AmountMinor      int64              `json:"amount_minor"`
	Currency         string             `json:"currency"`
	Status           string             `json:"status"`
	SelectedMethod   string             `json:"selected_method"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	QrPaymentID      pgtype.UUID        `json:"qr_payment_id"`
	CustomerEmail    string             `json:"customer_email"`
	ReturnUrl        string             `json:"return_url"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Dispute struct {
	ID          pgtype.UUID        `json:"id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Reason      *string            `json:"reason"`
	Status      string             `json:"status"`
	Evidence    []byte             `json:"evidence"`
	NetworkRef  *string            `json:"network_ref"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LedgerEntry struct {
	ID          pgtype.UUID        `json:"id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	EntryType   string             `json:"entry_type"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	ApiKeyHash         string             `json:"api_key_hash"`
	Mcc                *string            `json:"mcc"`
	SettlementCurrency string             `json:"settlement_currency"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WebhookUrl         *string            `json:"webhook_url"`
	WebhookSecretHash  *string            `json:"webhook_secret_hash"`
	WebhookSecretEnc   []byte             `json:"webhook_secret_enc"`
}

type MerchantUser struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	AvatarUrl     string             `json:"avatar_url"`
	OauthProvider string             `json:"oauth_provider"`
	OauthSubject  string             `json:"oauth_subject"`
	Role          string             `json:"role"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                  pgtype.UUID        `json:"id"`
	MerchantID          pgtype.UUID        `json:"merchant_id"`
	AmountMinor         int64              `json:"amount_minor"`
	CapturedAmountMinor int64              `json:"captured_amount_minor"`
	RefundedAmountMinor int64              `json:"refunded_amount_minor"`
	Currency            string             `json:"currency"`
	Status              string             `json:"status"`
	CardBrand           *string            `json:"card_brand"`
	CardLast4           *string            `json:"card_last4"`
	AcquirerRef         *string            `json:"acquirer_ref"`
	AuthCode            *string            `json:"auth_code"`
	Reference           *string            `json:"reference"`
	IdempotencyKey      string             `json:"idempotency_key"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type PaymentLink struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	PublicID       string             `json:"public_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	AllowedMethods []string           `json:"allowed_methods"`
	LinkType       string             `json:"link_type"`
	Status         string             `json:"status"`
	Reference      string             `json:"reference"`
	ImageUrl       string             `json:"image_url"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Payout struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Currency      string             `json:"currency"`
	GrossMinor    int64              `json:"gross_minor"`
	RefundedMinor int64              `json:"refunded_minor"`
	FeeMinor      int64              `json:"fee_minor"`
	NetMinor      int64              `json:"net_minor"`
	PaymentCount  int32              `json:"payment_count"`
	Status        string             `json:"status"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QrPayment struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	Method         string             `json:"method"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	Reference      string             `json:"reference"`
	QrPayload      string             `json:"qr_payload"`
	QrImageUrl     *string            `json:"qr_image_url"`
	PayerBank      *string            `json:"payer_bank"`
	ProviderRef    *string            `json:"provider_ref"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CorrelationRef *string            `json:"correlation_ref"`
}

type ReconMismatch struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Currency      string             `json:"currency"`
	LedgerMinor   int64              `json:"ledger_minor"`
	AcquirerMinor int64              `json:"acquirer_minor"`
	DeltaMinor    int64              `json:"delta_minor"`
	ReportDate    pgtype.Date        `json:"report_date"`
	Resolved      bool               `json:"resolved"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Refund struct {
	ID          pgtype.UUID        `json:"id"`
	PaymentID   pgtype.UUID        `json:"payment_id"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Reason      *string            `json:"reason"`
	AcquirerRef *string            `json:"acquirer_ref"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WebhookEvent struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Delivered     bool               `json:"delivered"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	Failed        bool               `json:"failed"`
	LastError     *string            `json:"last_error"`
	TargetUrl     *string            `json:"target_url"`
}
