// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateCapturedForSettlement = `-- name: AggregateCapturedForSettlement :many


SELECT
    merchant_id,
    currency,
    SUM(captured_amount_minor)::BIGINT AS gross_minor,
    SUM(refunded_amount_minor)::BIGINT AS refunded_minor,
    COUNT(*)::BIGINT                    AS payment_count
FROM payments
WHERE status IN ('captured', 'partial_refunded', 'refunded')
  AND updated_at >= $1
  AND updated_at <  $2
GROUP BY merchant_id, currency
`

type AggregateCapturedForSettlementParams struct {
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedAt_2 pgtype.Timestamptz `json:"updated_at_2"`
}

type AggregateCapturedForSettlementRow struct {
	MerchantID    pgtype.UUID `json:"merchant_id"`
	Currency      string      `json:"currency"`
	GrossMinor    int64       `json:"gross_minor"`
	RefundedMinor int64       `json:"refunded_minor"`
	PaymentCount  int64       `json:"payment_count"`
}

// internal/repository/queries/ops.sql
// Data access for the background ops workers: settlement, reconciliation and
// outbound webhook delivery. All parameters are bound ($1, $2, ...).
// Settlement: aggregate captured (net of refunded) payments per merchant/currency
// within a time window. Only captured/partial_refunded/refunded rows have moved
// money and are eligible for payout.
func (q *Queries) AggregateCapturedForSettlement(ctx context.Context, arg AggregateCapturedForSettlementParams) ([]AggregateCapturedForSettlementRow, error) {
	rows, err := q.db.Query(ctx, aggregateCapturedForSettlement, arg.UpdatedAt, arg.UpdatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateCapturedForSettlementRow
	for rows.Next() {
		var i AggregateCapturedForSettlementRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Currency,
			&i.GrossMinor,
			&i.RefundedMinor,
			&i.PaymentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (
    id, merchant_id, currency, gross_minor, refunded_minor, fee_minor, net_minor,
    payment_count, status, period_start, period_end
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, merchant_id, currency, gross_minor, refunded_minor, fee_minor, net_minor, payment_count, status, period_start, period_end, created_at
`

type CreatePayoutParams struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Currency      string             `json:"currency"`
	GrossMinor    int64              `json:"gross_minor"`
	RefundedMinor int64              `json:"refunded_minor"`
	FeeMinor      int64              `json:"fee_minor"`
	NetMinor      int64              `json:"net_minor"`
	PaymentCount  int32              `json:"payment_count"`
	Status        string             `json:"status"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.ID,
		arg.MerchantID,
		arg.Currency,
		arg.GrossMinor,
		arg.RefundedMinor,
		arg.FeeMinor,
		arg.NetMinor,
		arg.PaymentCount,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Currency,
		&i.GrossMinor,
		&i.RefundedMinor,
		&i.FeeMinor,
		&i.NetMinor,
		&i.PaymentCount,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const createReconMismatch = `-- name: CreateReconMismatch :exec
INSERT INTO recon_mismatches (
    id, merchant_id, currency, ledger_minor, acquirer_minor, delta_minor, report_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateReconMismatchParams struct {
	ID            pgtype.UUID `json:"id"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
	Currency      string      `json:"currency"`
	LedgerMinor   int64       `json:"ledger_minor"`
	AcquirerMinor int64       `json:"acquirer_minor"`
	DeltaMinor    int64       `json:"delta_minor"`
	ReportDate    pgtype.Date `json:"report_date"`
}

func (q *Queries) CreateReconMismatch(ctx context.Context, arg CreateReconMismatchParams) error {
	_, err := q.db.Exec(ctx, createReconMismatch,
		arg.ID,
		arg.MerchantID,
		arg.Currency,
		arg.LedgerMinor,
		arg.AcquirerMinor,
		arg.DeltaMinor,
		arg.ReportDate,
	)
	return err
}

const ledgerCapturedTotals = `-- name: LedgerCapturedTotals :many

SELECT
    p.merchant_id                                    AS merchant_id,
    l.currency                                       AS currency,
    COALESCE(SUM(
        CASE WHEN l.entry_type = 'capture' THEN l.amount_minor
             WHEN l.entry_type = 'refund'  THEN -l.amount_minor
             ELSE 0 END
    ), 0)::BIGINT                                    AS net_minor
FROM ledger_entries l
JOIN payments p ON p.id = l.payment_id
WHERE l.created_at >= $1 AND l.created_at < $2
GROUP BY p.merchant_id, l.currency
`

type LedgerCapturedTotalsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type LedgerCapturedTotalsRow struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Currency   string      `json:"currency"`
	NetMinor   int64       `json:"net_minor"`
}

// Reconciliation: ledger-side captured totals per merchant/currency. capture and
// settlement entries are additive; refund/void reduce the net.
func (q *Queries) LedgerCapturedTotals(ctx context.Context, arg LedgerCapturedTotalsParams) ([]LedgerCapturedTotalsRow, error) {
	rows, err := q.db.Query(ctx, ledgerCapturedTotals, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerCapturedTotalsRow
	for rows.Next() {
		var i LedgerCapturedTotalsRow
		if err := rows.Scan(&i.MerchantID, &i.Currency, &i.NetMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWebhooks = `-- name: ListPendingWebhooks :many

SELECT id, merchant_id, event_type, payload, delivered, attempts, next_attempt_at, created_at, delivered_at, failed, last_error, target_url FROM webhook_events
WHERE delivered = FALSE
  AND failed = FALSE
  AND (next_attempt_at IS NULL OR next_attempt_at <= NOW())
ORDER BY created_at
LIMIT $1
`

// Outbound webhook delivery.
func (q *Queries) ListPendingWebhooks(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listPendingWebhooks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.EventType,
			&i.Payload,
			&i.Delivered,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.Failed,
			&i.LastError,
			&i.TargetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_events
SET delivered = TRUE,
    delivered_at = NOW(),
    attempts = attempts + 1,
    last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, id)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_events
SET failed = TRUE,
    attempts = attempts + 1,
    last_error = $2
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.ID, arg.LastError)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE webhook_events
SET attempts = attempts + 1,
    next_attempt_at = $2,
    last_error = $3
WHERE id = $1
`

type MarkWebhookRetryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
