// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (
    id, merchant_id, amount_minor, currency, status,
    card_brand, card_last4, reference, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at
`

type CreatePaymentParams struct {
	ID             pgtype.UUID `json:"id"`
	MerchantID     pgtype.UUID `json:"merchant_id"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       string      `json:"currency"`
	Status         string      `json:"status"`
	CardBrand      *string     `json:"card_brand"`
	CardLast4      *string     `json:"card_last4"`
	Reference      *string     `json:"reference"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// internal/repository/queries/payment.sql
// sqlc generates type-safe Go from these queries. All parameters are bound
// ($1, $2, ...) so there is no SQL-injection surface.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.MerchantID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.CardBrand,
		arg.CardLast4,
		arg.Reference,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.CapturedAmountMinor,
		&i.RefundedAmountMinor,
		&i.Currency,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.AcquirerRef,
		&i.AuthCode,
		&i.Reference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one
SELECT id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at FROM payments
WHERE merchant_id = $1 AND idempotency_key = $2
`

type GetByIdempotencyKeyParams struct {
	MerchantID     pgtype.UUID `json:"merchant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetByIdempotencyKey(ctx context.Context, arg GetByIdempotencyKeyParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, arg.MerchantID, arg.IdempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.CapturedAmountMinor,
		&i.RefundedAmountMinor,
		&i.Currency,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.AcquirerRef,
		&i.AuthCode,
		&i.Reference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.CapturedAmountMinor,
		&i.RefundedAmountMinor,
		&i.Currency,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.AcquirerRef,
		&i.AuthCode,
		&i.Reference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentForMerchant = `-- name: GetPaymentForMerchant :one
SELECT id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at FROM payments WHERE id = $1 AND merchant_id = $2
`

type GetPaymentForMerchantParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// Merchant-scoped fetch: only returns the row when it belongs to the
// authenticated merchant, avoiding a cross-tenant existence oracle (returns
// ErrNoRows -> 404 when the id belongs to another merchant).
func (q *Queries) GetPaymentForMerchant(ctx context.Context, arg GetPaymentForMerchantParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForMerchant, arg.ID, arg.MerchantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.CapturedAmountMinor,
		&i.RefundedAmountMinor,
		&i.Currency,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.AcquirerRef,
		&i.AuthCode,
		&i.Reference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (
    id, payment_id, entry_type, amount_minor, currency, created_at
) VALUES ($1, $2, $3, $4, $5, NOW())
`

type InsertLedgerEntryParams struct {
	ID          pgtype.UUID `json:"id"`
	PaymentID   pgtype.UUID `json:"payment_id"`
	EntryType   string      `json:"entry_type"`
	AmountMinor int64       `json:"amount_minor"`
	Currency    string      `json:"currency"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.PaymentID,
		arg.EntryType,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const listPaymentsByMerchant = `-- name: ListPaymentsByMerchant :many
SELECT id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at FROM payments
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListPaymentsByMerchant(ctx context.Context, arg ListPaymentsByMerchantParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.AmountMinor,
			&i.CapturedAmountMinor,
			&i.RefundedAmountMinor,
			&i.Currency,
			&i.Status,
			&i.CardBrand,
			&i.CardLast4,
			&i.AcquirerRef,
			&i.AuthCode,
			&i.Reference,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    captured_amount_minor = $3,
    refunded_amount_minor = $4,
    acquirer_ref = $5,
    auth_code = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, merchant_id, amount_minor, captured_amount_minor, refunded_amount_minor, currency, status, card_brand, card_last4, acquirer_ref, auth_code, reference, idempotency_key, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID                  pgtype.UUID `json:"id"`
	Status              string      `json:"status"`
	CapturedAmountMinor int64       `json:"captured_amount_minor"`
	RefundedAmountMinor int64       `json:"refunded_amount_minor"`
	AcquirerRef         *string     `json:"acquirer_ref"`
	AuthCode            *string     `json:"auth_code"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.CapturedAmountMinor,
		arg.RefundedAmountMinor,
		arg.AcquirerRef,
		arg.AuthCode,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AmountMinor,
		&i.CapturedAmountMinor,
		&i.RefundedAmountMinor,
		&i.Currency,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.AcquirerRef,
		&i.AuthCode,
		&i.Reference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_log (
    id, actor, action, entity_type, entity_id, metadata, created_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type WriteAuditLogParams struct {
	ID         pgtype.UUID `json:"id"`
	Actor      string      `json:"actor"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.ID,
		arg.Actor,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}
