// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_link.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePaymentLinkIfActive = `-- name: ConsumePaymentLinkIfActive :one
UPDATE payment_links SET status = 'paid', updated_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND status = 'active'
RETURNING id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at
`

type ConsumePaymentLinkIfActiveParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// Atomically flips an active link to 'paid'. Returns no row if the link is not
// active (already paid/disabled/expired) — the caller uses that to prevent
// double payment of a single_use link.
func (q *Queries) ConsumePaymentLinkIfActive(ctx context.Context, arg ConsumePaymentLinkIfActiveParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, consumePaymentLinkIfActive, arg.ID, arg.MerchantID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentLink = `-- name: CreatePaymentLink :one

INSERT INTO payment_links (
    id, merchant_id, public_id, title, description, amount_minor, currency,
    allowed_methods, link_type, status, reference, image_url, expires_at, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at
`

type CreatePaymentLinkParams struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	PublicID       string             `json:"public_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	AllowedMethods []string           `json:"allowed_methods"`
	LinkType       string             `json:"link_type"`
	Status         string             `json:"status"`
	Reference      string             `json:"reference"`
	ImageUrl       string             `json:"image_url"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

// internal/repository/queries/payment_link.sql
// Payment links CRUD. Reads/updates are ALWAYS scoped by merchant_id to prevent
// one merchant reading/altering another's link (IDOR); the public_id lookup is
// the only unscoped read and is used by the (Phase 3) public checkout page.
func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, createPaymentLink,
		arg.ID,
		arg.MerchantID,
		arg.PublicID,
		arg.Title,
		arg.Description,
		arg.AmountMinor,
		arg.Currency,
		arg.AllowedMethods,
		arg.LinkType,
		arg.Status,
		arg.Reference,
		arg.ImageUrl,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentLink = `-- name: GetPaymentLink :one
SELECT id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at FROM payment_links WHERE id = $1 AND merchant_id = $2
`

type GetPaymentLinkParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetPaymentLink(ctx context.Context, arg GetPaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLink, arg.ID, arg.MerchantID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentLinkByPublicID = `-- name: GetPaymentLinkByPublicID :one
SELECT id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at FROM payment_links WHERE public_id = $1
`

func (q *Queries) GetPaymentLinkByPublicID(ctx context.Context, publicID string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLinkByPublicID, publicID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentLinksByMerchant = `-- name: ListPaymentLinksByMerchant :many
SELECT id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at FROM payment_links
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentLinksByMerchantParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListPaymentLinksByMerchant(ctx context.Context, arg ListPaymentLinksByMerchantParams) ([]PaymentLink, error) {
	rows, err := q.db.Query(ctx, listPaymentLinksByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentLink
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PublicID,
			&i.Title,
			&i.Description,
			&i.AmountMinor,
			&i.Currency,
			&i.AllowedMethods,
			&i.LinkType,
			&i.Status,
			&i.Reference,
			&i.ImageUrl,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePaymentLinkReservation = `-- name: ReleasePaymentLinkReservation :one
UPDATE payment_links SET status = 'active', updated_at = NOW()
WHERE id = $1 AND merchant_id = $2 AND status = 'paid'
RETURNING id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at
`

type ReleasePaymentLinkReservationParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// Reverts a link reserved by an in-flight charge back to 'active', but ONLY if it
// is still 'paid' (the reserved state). If the status changed meanwhile (e.g. a
// concurrent Disable set it 'disabled'), this affects no row and that change is
// preserved — so releasing a failed charge can never silently undo a disable.
func (q *Queries) ReleasePaymentLinkReservation(ctx context.Context, arg ReleasePaymentLinkReservationParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, releasePaymentLinkReservation, arg.ID, arg.MerchantID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentLinkStatus = `-- name: UpdatePaymentLinkStatus :one
UPDATE payment_links
SET status = $3, updated_at = NOW()
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, public_id, title, description, amount_minor, currency, allowed_methods, link_type, status, reference, image_url, expires_at, created_by, created_at, updated_at
`

type UpdatePaymentLinkStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	Status     string      `json:"status"`
}

func (q *Queries) UpdatePaymentLinkStatus(ctx context.Context, arg UpdatePaymentLinkStatusParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, updatePaymentLinkStatus, arg.ID, arg.MerchantID, arg.Status)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.AllowedMethods,
		&i.LinkType,
		&i.Status,
		&i.Reference,
		&i.ImageUrl,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
