// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qr.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQRPayment = `-- name: CreateQRPayment :one

INSERT INTO qr_payments (
    id, merchant_id, method, amount_minor, currency, status,
    reference, qr_payload, qr_image_url, provider_ref, correlation_ref, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref
`

type CreateQRPaymentParams struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	Method         string             `json:"method"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	Reference      string             `json:"reference"`
	QrPayload      string             `json:"qr_payload"`
	QrImageUrl     *string            `json:"qr_image_url"`
	ProviderRef    *string            `json:"provider_ref"`
	CorrelationRef *string            `json:"correlation_ref"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// internal/repository/queries/qr.sql
// QR payment data access. QR is an async push model: mint on create, then the
// bank/PSP confirms via a signed webhook. All parameters are bound ($1, $2, ...)
// so there is no SQL-injection surface.
func (q *Queries) CreateQRPayment(ctx context.Context, arg CreateQRPaymentParams) (QrPayment, error) {
	row := q.db.QueryRow(ctx, createQRPayment,
		arg.ID,
		arg.MerchantID,
		arg.Method,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.Reference,
		arg.QrPayload,
		arg.QrImageUrl,
		arg.ProviderRef,
		arg.CorrelationRef,
		arg.ExpiresAt,
	)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :exec
INSERT INTO webhook_events (
    id, merchant_id, event_type, payload, next_attempt_at, created_at
) VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreateWebhookEventParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	EventType  string      `json:"event_type"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error {
	_, err := q.db.Exec(ctx, createWebhookEvent,
		arg.ID,
		arg.MerchantID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const getQRByCorrelationRef = `-- name: GetQRByCorrelationRef :one
SELECT id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref FROM qr_payments WHERE correlation_ref = $1
`

// Correlates an inbound webhook back to the minted QR via the stable
// correlation_ref. Used for PromptPay, whose webhook echoes the reference we
// embedded in the EMVCo tag-62 payload at creation.
func (q *Queries) GetQRByCorrelationRef(ctx context.Context, correlationRef *string) (QrPayment, error) {
	row := q.db.QueryRow(ctx, getQRByCorrelationRef, correlationRef)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}

const getQRByProviderRef = `-- name: GetQRByProviderRef :one
SELECT id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref FROM qr_payments WHERE provider_ref = $1
`

func (q *Queries) GetQRByProviderRef(ctx context.Context, providerRef *string) (QrPayment, error) {
	row := q.db.QueryRow(ctx, getQRByProviderRef, providerRef)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}

const getQRPayment = `-- name: GetQRPayment :one
SELECT id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref FROM qr_payments WHERE id = $1
`

func (q *Queries) GetQRPayment(ctx context.Context, id pgtype.UUID) (QrPayment, error) {
	row := q.db.QueryRow(ctx, getQRPayment, id)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}

const getQRPaymentForMerchant = `-- name: GetQRPaymentForMerchant :one
SELECT id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref FROM qr_payments WHERE id = $1 AND merchant_id = $2
`

type GetQRPaymentForMerchantParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

// Merchant-scoped fetch: only returns the row when it belongs to the
// authenticated merchant (returns ErrNoRows -> 404 for another merchant's id).
func (q *Queries) GetQRPaymentForMerchant(ctx context.Context, arg GetQRPaymentForMerchantParams) (QrPayment, error) {
	row := q.db.QueryRow(ctx, getQRPaymentForMerchant, arg.ID, arg.MerchantID)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}

const getQRPaymentWithMerchant = `-- name: GetQRPaymentWithMerchant :one
SELECT q.id, q.merchant_id, m.name AS merchant_name, q.method,
       q.amount_minor, q.currency, q.status, q.reference,
       q.provider_ref, q.correlation_ref, q.expires_at, q.paid_at, q.created_at
FROM qr_payments q
JOIN merchants m ON m.id = q.merchant_id
WHERE q.id = $1
`

type GetQRPaymentWithMerchantRow struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	MerchantName   string             `json:"merchant_name"`
	Method         string             `json:"method"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	Reference      string             `json:"reference"`
	ProviderRef    *string            `json:"provider_ref"`
	CorrelationRef *string            `json:"correlation_ref"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Sandbox display fetch: a single QR payment joined to the owning merchant's
// name so the payer simulator can show "who is charging". Unauthenticated
// (sandbox only); returns display fields plus the correlation/provider handles
// the server needs to sign a confirmation, never any secret.
func (q *Queries) GetQRPaymentWithMerchant(ctx context.Context, id pgtype.UUID) (GetQRPaymentWithMerchantRow, error) {
	row := q.db.QueryRow(ctx, getQRPaymentWithMerchant, id)
	var i GetQRPaymentWithMerchantRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MerchantName,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.ProviderRef,
		&i.CorrelationRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingQRPayments = `-- name: ListPendingQRPayments :many
SELECT q.id, q.merchant_id, m.name AS merchant_name, q.method,
       q.amount_minor, q.currency, q.status, q.reference, q.created_at
FROM qr_payments q
JOIN merchants m ON m.id = q.merchant_id
WHERE q.status = $1
ORDER BY q.created_at DESC
LIMIT $2
`

type ListPendingQRPaymentsParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

type ListPendingQRPaymentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	MerchantID   pgtype.UUID        `json:"merchant_id"`
	MerchantName string             `json:"merchant_name"`
	Method       string             `json:"method"`
	AmountMinor  int64              `json:"amount_minor"`
	Currency     string             `json:"currency"`
	Status       string             `json:"status"`
	Reference    string             `json:"reference"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Recent QR payments in a given status, joined to the owning merchant's name,
// most recent first. Powers the sandbox simulator's "incoming requests" list.
// Unauthenticated (sandbox only); returns display fields, never secrets.
func (q *Queries) ListPendingQRPayments(ctx context.Context, arg ListPendingQRPaymentsParams) ([]ListPendingQRPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPendingQRPayments, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingQRPaymentsRow
	for rows.Next() {
		var i ListPendingQRPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.MerchantName,
			&i.Method,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQRStatus = `-- name: UpdateQRStatus :one
UPDATE qr_payments
SET status = $2,
    payer_bank = $3,
    provider_ref = $4,
    paid_at = $5
WHERE id = $1
RETURNING id, merchant_id, method, amount_minor, currency, status, reference, qr_payload, qr_image_url, payer_bank, provider_ref, expires_at, paid_at, created_at, correlation_ref
`

type UpdateQRStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	PayerBank   *string            `json:"payer_bank"`
	ProviderRef *string            `json:"provider_ref"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateQRStatus(ctx context.Context, arg UpdateQRStatusParams) (QrPayment, error) {
	row := q.db.QueryRow(ctx, updateQRStatus,
		arg.ID,
		arg.Status,
		arg.PayerBank,
		arg.ProviderRef,
		arg.PaidAt,
	)
	var i QrPayment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Method,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reference,
		&i.QrPayload,
		&i.QrImageUrl,
		&i.PayerBank,
		&i.ProviderRef,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CorrelationRef,
	)
	return i, err
}
