// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// internal/repository/queries/ops.sql
	// Data access for the background ops workers: settlement, reconciliation and
	// outbound webhook delivery. All parameters are bound ($1, $2, ...).
	// Settlement: aggregate captured (net of refunded) payments per merchant/currency
	// within a time window. Only captured/partial_refunded/refunded rows have moved
	// money and are eligible for payout.
	AggregateCapturedForSettlement(ctx context.Context, arg AggregateCapturedForSettlementParams) ([]AggregateCapturedForSettlementRow, error)
	// Atomically flips an active link to 'paid'. Returns no row if the link is not
	// active (already paid/disabled/expired) — the caller uses that to prevent
	// double payment of a single_use link.
	ConsumePaymentLinkIfActive(ctx context.Context, arg ConsumePaymentLinkIfActiveParams) (PaymentLink, error)
	// Chargeback count for a merchant over the same window, used to derive the
	// chargeback ratio against total payment count.
	CountDisputesByMerchant(ctx context.Context, arg CountDisputesByMerchantParams) (int64, error)
	// internal/repository/queries/checkout_session.sql
	// Hosted-checkout sessions. A session is ALWAYS resolved by its token hash (the
	// token is the credential); the merchant scope comes from the resolved row, not
	// from the caller. Updates are by primary key (already resolved from the hash).
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error)
	// internal/repository/queries/dispute.sql
	// Chargeback / dispute data access. State machine transitions are enforced in
	// the service layer; these queries persist the resulting rows. All parameters
	// are bound ($1, $2, ...).
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	// internal/repository/queries/merchant.sql
	// Merchant onboarding and lookup. The raw API key is never stored — only its
	// hash (api_key_hash). Auth resolves a merchant by hashing the presented key and
	// matching it here. All parameters are bound ($1, $2, ...).
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateMerchantUser(ctx context.Context, arg CreateMerchantUserParams) (MerchantUser, error)
	// internal/repository/queries/payment.sql
	// sqlc generates type-safe Go from these queries. All parameters are bound
	// ($1, $2, ...) so there is no SQL-injection surface.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// internal/repository/queries/payment_link.sql
	// Payment links CRUD. Reads/updates are ALWAYS scoped by merchant_id to prevent
	// one merchant reading/altering another's link (IDOR); the public_id lookup is
	// the only unscoped read and is used by the (Phase 3) public checkout page.
	CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	// internal/repository/queries/qr.sql
	// QR payment data access. QR is an async push model: mint on create, then the
	// bank/PSP confirms via a signed webhook. All parameters are bound ($1, $2, ...)
	// so there is no SQL-injection surface.
	CreateQRPayment(ctx context.Context, arg CreateQRPaymentParams) (QrPayment, error)
	CreateReconMismatch(ctx context.Context, arg CreateReconMismatchParams) error
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error
	GetByIdempotencyKey(ctx context.Context, arg GetByIdempotencyKeyParams) (Payment, error)
	GetCheckoutSessionByTokenHash(ctx context.Context, sessionTokenHash string) (CheckoutSession, error)
	GetDispute(ctx context.Context, id pgtype.UUID) (Dispute, error)
	GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error)
	GetMerchantByAPIKeyHash(ctx context.Context, apiKeyHash string) (Merchant, error)
	GetMerchantUserByID(ctx context.Context, id pgtype.UUID) (MerchantUser, error)
	// internal/repository/queries/merchant_user.sql
	// Dashboard human identities. Login resolves a user by (provider, subject); a
	// first-time identity is created together with its merchant by the service layer.
	GetMerchantUserByOAuth(ctx context.Context, arg GetMerchantUserByOAuthParams) (MerchantUser, error)
	// Returns the merchant's envelope-encrypted webhook signing key (NULL when the
	// merchant never set a webhook). The outbound worker decrypts it to sign a
	// delivery with the merchant's own key, falling back to the global key on NULL.
	// (Named "...SigningKey", not "...Secret", so the sqlc-generated query const
	// does not trip gosec G101's hardcoded-credential name pattern; the value is a
	// parameterized query selecting a column, never a literal secret.)
	GetMerchantWebhookSigningKey(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	// Merchant-scoped fetch: only returns the row when it belongs to the
	// authenticated merchant, avoiding a cross-tenant existence oracle (returns
	// ErrNoRows -> 404 when the id belongs to another merchant).
	GetPaymentForMerchant(ctx context.Context, arg GetPaymentForMerchantParams) (Payment, error)
	GetPaymentLink(ctx context.Context, arg GetPaymentLinkParams) (PaymentLink, error)
	GetPaymentLinkByPublicID(ctx context.Context, publicID string) (PaymentLink, error)
	// Correlates an inbound webhook back to the minted QR via the stable
	// correlation_ref. Used for PromptPay, whose webhook echoes the reference we
	// embedded in the EMVCo tag-62 payload at creation.
	GetQRByCorrelationRef(ctx context.Context, correlationRef *string) (QrPayment, error)
	GetQRByProviderRef(ctx context.Context, providerRef *string) (QrPayment, error)
	GetQRPayment(ctx context.Context, id pgtype.UUID) (QrPayment, error)
	// Merchant-scoped fetch: only returns the row when it belongs to the
	// authenticated merchant (returns ErrNoRows -> 404 for another merchant's id).
	GetQRPaymentForMerchant(ctx context.Context, arg GetQRPaymentForMerchantParams) (QrPayment, error)
	// Sandbox display fetch: a single QR payment joined to the owning merchant's
	// name so the payer simulator can show "who is charging". Unauthenticated
	// (sandbox only); returns display fields plus the correlation/provider handles
	// the server needs to sign a confirmation, never any secret.
	GetQRPaymentWithMerchant(ctx context.Context, id pgtype.UUID) (GetQRPaymentWithMerchantRow, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	// Reconciliation: ledger-side captured totals per merchant/currency. capture and
	// settlement entries are additive; refund/void reduce the net.
	LedgerCapturedTotals(ctx context.Context, arg LedgerCapturedTotalsParams) ([]LedgerCapturedTotalsRow, error)
	ListAllDisputes(ctx context.Context, arg ListAllDisputesParams) ([]Dispute, error)
	// internal/repository/queries/admin.sql
	// Platform (admin) read models behind X-Admin-Key. These are intentionally
	// unscoped by merchant — they power the operator console. All parameters are
	// bound ($1, $2, ...) so there is no SQL-injection surface.
	ListAllMerchants(ctx context.Context, arg ListAllMerchantsParams) ([]Merchant, error)
	// Platform-wide settlement / payout rows for the admin console, most recent
	// first. Unscoped (admin-only) — authorization is enforced by AdminAuth.
	ListAllPayouts(ctx context.Context, limit int32) ([]Payout, error)
	ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error)
	ListDisputesByMerchant(ctx context.Context, arg ListDisputesByMerchantParams) ([]Dispute, error)
	ListDisputesByPayment(ctx context.Context, paymentID pgtype.UUID) ([]Dispute, error)
	ListPaymentLinksByMerchant(ctx context.Context, arg ListPaymentLinksByMerchantParams) ([]PaymentLink, error)
	ListPaymentsByMerchant(ctx context.Context, arg ListPaymentsByMerchantParams) ([]Payment, error)
	// Settlement / payout rows for a merchant, most recent first.
	ListPayoutsByMerchant(ctx context.Context, arg ListPayoutsByMerchantParams) ([]Payout, error)
	// Recent QR payments in a given status, joined to the owning merchant's name,
	// most recent first. Powers the sandbox simulator's "incoming requests" list.
	// Unauthenticated (sandbox only); returns display fields, never secrets.
	ListPendingQRPayments(ctx context.Context, arg ListPendingQRPaymentsParams) ([]ListPendingQRPaymentsRow, error)
	// Outbound webhook delivery.
	ListPendingWebhooks(ctx context.Context, limit int32) ([]WebhookEvent, error)
	// internal/repository/queries/transaction.sql
	// Unified transaction feed for the merchant dashboard: a UNION ALL over the
	// three payment-activity tables (card, PromptPay, wallet), each already
	// storing money as amount_minor BIGINT + currency (no decimal conversion
	// needed). Avoiding double-counting:
	//   * payments        -> source 'card'      (every card payment).
	//   * qr_payments     -> source 'promptpay' (every QR payment).
	//   * checkout_sessions -> source 'wallet', ONLY rows that are paid AND whose
	//     selected_method is a wallet method. Card/PromptPay checkout sessions
	//     already surface via payments/qr_payments above; wallet mocks never
	//     create a payments/qr_payments row, so this is the only place they
	//     appear.
	// All parameters are bound ($1..$5) so there is no SQL-injection surface. The
	// merchant id is repeated as $1/$2/$3 (one per UNIONed branch, all bound to
	// the SAME value by the caller) rather than reused positionally: sqlc's
	// analyzer resolves a shared parameter against every branch's FROM clause at
	// once and misreports merchant_id as ambiguous when the same ordinal is reused
	// across a UNION, even though plain Postgres accepts it (verified via
	// PREPARE). Distinct ordinals per branch sidesteps that false positive.
	ListTransactionsByMerchant(ctx context.Context, arg ListTransactionsByMerchantParams) ([]ListTransactionsByMerchantRow, error)
	MarkWebhookDelivered(ctx context.Context, id pgtype.UUID) error
	MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error
	MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error
	// internal/repository/queries/dashboard.sql
	// Merchant Dashboard read models: KPI aggregation over payments, the merchant's
	// own settlement/payout rows, and its full dispute list. Everything is scoped to
	// the authenticated merchant id ($1) so there is no cross-tenant leakage. All
	// parameters are bound ($1, $2, ...) so there is no SQL-injection surface.
	// One-row KPI rollup for a merchant over an inclusive [from, to] window. Volume
	// is captured (net-of-refund) money in minor units; the by-status counts drive
	// the dashboard tiles and the success / refund ratios. authorized here means
	// "reached authorized or beyond" (authorized|captured|partial_refunded|refunded)
	// so the success rate reflects payments that were approved by the acquirer.
	MerchantStats(ctx context.Context, arg MerchantStatsParams) (MerchantStatsRow, error)
	// Platform-wide key risk indicators across every merchant. Volume is captured
	// (net-of-refund) minor units. merchant_count is a cheap correlated count.
	PlatformStats(ctx context.Context) (PlatformStatsRow, error)
	// Reverts a link reserved by an in-flight charge back to 'active', but ONLY if it
	// is still 'paid' (the reserved state). If the status changed meanwhile (e.g. a
	// concurrent Disable set it 'disabled'), this affects no row and that change is
	// preserved — so releasing a failed charge can never silently undo a disable.
	ReleasePaymentLinkReservation(ctx context.Context, arg ReleasePaymentLinkReservationParams) (PaymentLink, error)
	// Issues a new API key by replacing the stored hash. The previous hash no
	// longer resolves, so the old key is immediately invalidated. The raw key is
	// generated and returned by the service layer; only its hash is persisted here.
	RotateMerchantAPIKey(ctx context.Context, arg RotateMerchantAPIKeyParams) (Merchant, error)
	// Sets the merchant's outbound webhook URL and rotates its delivery signing
	// secret. Stores BOTH the SHA-256 hash (kept for continuity) and the
	// envelope-encrypted secret (webhook_secret_enc) so the outbound worker can
	// retrieve and sign each delivery with this merchant's own secret. The raw
	// secret is returned once by the service layer and never stored in clear.
	SetMerchantWebhook(ctx context.Context, arg SetMerchantWebhookParams) (Merchant, error)
	// Daily payment series for a merchant over the half-open window [from, to),
	// bucketed by UTC calendar day. Volume uses the SAME captured (net-of-refund)
	// definition as MerchantStats (captured/partial_refunded/refunded rows only);
	// count is every payment created that day regardless of status. Days with no
	// payments are simply absent from the result set — the service zero-fills them
	// so the dashboard sparkline has one point per day.
	StatsSeriesByDay(ctx context.Context, arg StatsSeriesByDayParams) ([]StatsSeriesByDayRow, error)
	TouchMerchantUserLogin(ctx context.Context, id pgtype.UUID) error
	UpdateCheckoutSession(ctx context.Context, arg UpdateCheckoutSessionParams) (CheckoutSession, error)
	UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (Dispute, error)
	UpdatePaymentLinkStatus(ctx context.Context, arg UpdatePaymentLinkStatusParams) (PaymentLink, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateQRStatus(ctx context.Context, arg UpdateQRStatusParams) (QrPayment, error)
	WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error
}

var _ Querier = (*Queries)(nil)
